#─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
#─████████████████───██████████████─████████████───████████████───██████████████─████████████████──────██████──██████─██████──██████─██████████████───
#─██░░░░░░░░░░░░██───██░░░░░░░░░░██─██░░░░░░░░████─██░░░░░░░░████─██░░░░░░░░░░██─██░░░░░░░░░░░░██──────██░░██──██░░██─██░░██──██░░██─██░░░░░░░░░░██───
#─██░░████████░░██───██░░██████████─██░░████░░░░██─██░░████░░░░██─██░░██████████─██░░████████░░██──────██░░██──██░░██─██░░██──██░░██─██░░██████░░██───
#─██░░██────██░░██───██░░██─────────██░░██──██░░██─██░░██──██░░██─██░░██─────────██░░██────██░░██──────██░░██──██░░██─██░░██──██░░██─██░░██──██░░██───
#─██░░████████░░██───██░░██████████─██░░██──██░░██─██░░██──██░░██─██░░██████████─██░░████████░░██──────██░░██████░░██─██░░██──██░░██─██░░██████░░████─
#─██░░░░░░░░░░░░██───██░░░░░░░░░░██─██░░██──██░░██─██░░██──██░░██─██░░░░░░░░░░██─██░░░░░░░░░░░░██──────██░░░░░░░░░░██─██░░██──██░░██─██░░░░░░░░░░░░██─
#─██░░██████░░████───██░░██████████─██░░██──██░░██─██░░██──██░░██─██░░██████████─██░░██████░░████──────██░░██████░░██─██░░██──██░░██─██░░████████░░██─
#─██░░██──██░░██─────██░░██─────────██░░██──██░░██─██░░██──██░░██─██░░██─────────██░░██──██░░██────────██░░██──██░░██─██░░██──██░░██─██░░██────██░░██─
#─██░░██──██░░██████─██░░██████████─██░░████░░░░██─██░░████░░░░██─██░░██████████─██░░██──██░░██████────██░░██──██░░██─██░░██████░░██─██░░████████░░██─
#─██░░██──██░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░████─██░░░░░░░░████─██░░░░░░░░░░██─██░░██──██░░░░░░██────██░░██──██░░██─██░░░░░░░░░░██─██░░░░░░░░░░░░██─
#─██████──██████████─██████████████─████████████───████████████───██████████████─██████──██████████────██████──██████─██████████████─████████████████─
#─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# Created by MrUniverse44
# v1.0.0-SNAPSHOT
#─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# Select server to send player
lobby-servers:
  - lobby

blacklist-servers:
  - lobby

hub-command:
  command: hub
  aliases:
    - lobby

# Enable the limit of players in a specified IP, disable this option with -1
ip_limiter:
  limit: 2
  kick-reason: "&cToo many connections from this IP address"

messages:
  # Message when player uses the hub command
  hub-command:
    # Connecting
    connecting: "&cRedderHub &8| &fConnecting to a hub server!"
    # This message appears when the player is already in a hub
    already: "&cRedderHub &8| &fYou are already on the hub server!"
