#
#  ░██████╗░█████╗░░█████╗░██████╗░███████╗██████╗░░░░░░░░░█████╗░░█████╗░██████╗░███████╗
#  ██╔════╝██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗░░░░░░░░██╔══██╗██╔══██╗██╔══██╗██╔════╝
#  ╚█████╗░██║░░╚═╝███████║██████╔╝█████╗░░██║░░██║░░░░░░░░██║░░╚═╝██║░░██║██████╔╝█████╗░░
#  ░╚═══██╗██║░░██╗██╔══██║██╔══██╗██╔══╝░░██║░░██║░░░░░░░░██║░░██╗██║░░██║██╔══██╗██╔══╝░░
#  ██████╔╝╚█████╔╝██║░░██║██║░░██║███████╗██████╔╝░░░░░░░░╚█████╔╝╚█████╔╝██║░░██║███████╗
#  ╚═════╝░░╚════╝░╚═╝░░╚═╝╚═╝░░╚═╝╚══════╝╚═════╝░░░░░░░░░░╚════╝░░╚════╝░╚═╝░░╚═╝╚══════╝
#
#─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# Created by MrUniverse44
# v2.0.0-SNAPSHOT
#─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# Select server to send player
lobby-servers:
  - lobby

blacklist-servers:
  - lobby

hub-command:
  command: hub
  aliases:
    - lobby

# Enable the limit of players in a specified IP, disable this option with -1
ip_limiter:
  limit: 2
  kick-reason: "&cToo many connections from this IP address"

# This command will debug the locale of a player when uses the hub command.
display-locale: false

# This will show the join motd for the hub command
join-motd: false

messages:
  # Message when player uses the hub command
  hub-command:
    default:
      # Connecting
      connecting: "&cScaredCore &8| &fConnecting to a hub server!"
      # This message appears when the player is already in a hub
      already: "&cScaredCore &8| &fYou are already on the hub server!"
      # This message appears when the players join to a hub server
      join-motd: "&aWelcome %player% to the hub server!"
    en:
      # Connecting
      connecting: "&cScaredCore &8| &fConnecting to a hub server!"
      # This message appears when the player is already in a hub
      already: "&cScaredCore &8| &fYou are already on the hub server!"
      # This message appears when the players join to a hub server
      join-motd: "&aWelcome %player% to the hub server!"
    es:
      # Connecting
      connecting: "&cScaredCore &8| &fConectandote a un servidor lobby!"
      # This message appears when the player is already in a hub
      already: "&cScaredCore &8| &fTu ya estas conectado en este servidor!"
      # This message appears when the players join to a hub server
      join-motd: "&aBienvenido %player% a el servidor de lobby!"
